name: using events in Github action pipelines

# on: workflow_dispatch
# on: push
on:
  pull_request:
    types:
      - opened

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - name: basic linux commands
        run: |
          ls
          pwd
          date
          uname -avr
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: use github internal information
        run: echo "${{github.event_name}}"
  deploy_job:
    runs-on: ubuntu-latest
    steps:
      - name: deploy application
        run: echo "deploying application"
