name: controlling execution flow in github actions

on:
  workflow_dispatch:
    inputs:
      pass-unit-tests:
        type: boolean
        description: whether to pass unit tests or not
        default: true

jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - name: "lint and build"
        run: echo "lint and build project"
  unit-test:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Running Unit Tests
        run: echo "Running unit tests...."
      - name: Failing steps
        if: ${{ !inputs.pass-unit-tests }}
        run: exit 1
  deploy-nonprod:
    runs-on: ubuntu-latest
    needs:
      - lint-build
      - unit-test
    steps:
      - name: "Deploy to Non Prod"
        run: echo "Deploying to Non Prod"
  e2e-tests:
    runs-on: ubuntu-latest
    needs:
      - deploy-nonprod
    steps:
      - name: "Running e2e tests..."
        run: echo "Running E2E Tests"
  load-tests:
    runs-on: ubuntu-latest
    needs:
      - deploy-nonprod
    steps:
      - name: "Running load tests..."
        run: echo "Running Load Tests"
  deploy-prod:
    runs-on: ubuntu-latest
    needs:
      - e2e-tests
      - load-tests
    steps:
      - name: "Deploy to Prod"
        run: echo "Deploying to Prod"
