name: Running workflow in slef hosted runner of github actions

on:
  workflow_dispatch:
    inputs:
      Aprove:
        description: "Approve workflow"
        required: true
        default: "Approve"
jobs:
  testjob:
    runs-on: self-hosted
    steps:
      - name: echo event name
        run: echo "${{github.event_name}}"
      - name: echo runner os
        run: echo "${{runner.os}}"
